version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/nextjs
    overwrite: true

permissions:
  - object: /
    pattern: "**"
    owner: root
    group: root

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300

  ApplicationStart:
    - location: scripts/server_start.sh
      timeout: 300
